import { Subestacao } from './types';

export const SUBESTACOES: Subestacao[] = [
  // Sul Fluminense / Vale do Café / Região Serrana / Centro-Sul
  { id: 'CEN', sigla: 'CEN', nome: 'CENTENÁRIO', endereco: 'RUA JOSE DO PATROCINIO, 578 - CARVALHEIRA - VASSOURAS' },
  { id: 'AVL', sigla: 'AVL', nome: 'AVELAR', endereco: 'ESTRADA RJ CENTO E VINTE E CINCO, 2482 - AVELAR - PATY DO ALFERES' },
  { id: 'BVD', sigla: 'BVD', nome: 'BELVEDERE', endereco: 'ESTRADA BARRA DO PIRAI IPIABAS, 319 - BELVEDERE - BARRA DO PIRAI' },
  { id: 'QMC', sigla: 'QMC', nome: 'QUIMICA', endereco: 'RUA ALEXANDRE GOMES LEAL, 15 - QUIMICA - BARRA DO PIRAI' },
  { id: 'IPB', sigla: 'IPB', nome: 'IPIABAS', endereco: 'RUA PRESIDENTE PEDREIRA, 12010 - IPIABAS - BARRA DO PIRAI' },
  { id: 'GTL', sigla: 'GTL', nome: 'GETULANDIA', endereco: 'RODOVIA PRESIDENTE VARGAS, 12001 - SANTA CLARA - BARRA MANSA' },
  { id: 'MTH', sigla: 'MTH', nome: 'MONTANHES', endereco: 'RUA ORLANDO SILVA, 1199 - KM OITENTA E QUATRO - PIRAI' },
  { id: 'SCI', sigla: 'SCI', nome: 'SANTA CECILIA', endereco: 'RUA CRISTIANO OTONI, 1411 - CENTRO(BP) - BARRA DO PIRAI' },
  { id: 'VGA', sigla: 'VGA', nome: 'VARGEM ALEGRE', endereco: 'TRAVESSA JOSE HILARIO DE PAULA, 125 - VARGEM ALEGRE - BARRA DO PIRAI' },
  { id: 'TRS', sigla: 'TRS', nome: 'TRES RIOS', endereco: 'ESTRADA PASSATEMPO, 102 - CANTAGALO - TRES RIOS' },
  { id: 'RFL', sigla: 'RFL', nome: 'RIO DAS FLORES', endereco: 'AVENIDA DOUTORA VILMA DUTRA NOVAES, 54518 - CENTRO(RF) - RIO DAS FLORES' },
  { id: 'TUV', sigla: 'TUV', nome: 'TURVO', endereco: 'RUA ULISSES DIAS VALENTE, 920 - SAO JOSE DO TURVO - BARRA DO PIRAI' },
  { id: 'VIG', sigla: 'VIG', nome: 'VIGARIO', endereco: 'RUA JORNALISTA MOACIR PADILHA, 34 - CENTRO(PI) - PIRAI' },
  { id: 'PIN', sigla: 'PIN', nome: 'PINHEIRAL', endereco: 'RUA JOSE GOMES SILVA JUNIOR, 152 - CENTRO(PIN) - PINHEIRAL' },
  { id: 'MBR', sigla: 'MBR', nome: 'MOURA BRASIL', endereco: 'RUA MALIBU DE SANTA TEREZINHA, 2 - MOURA BRASIL - TRES RIOS' },
  { id: 'PBS', sigla: 'PBS', nome: 'PARAIBA DO SUL', endereco: 'ALAMEDA PARAIBA, 333 - CENTRO(PS) - PARAIBA DO SUL' },
  { id: 'MSG', sigla: 'MSG', nome: 'MORSING', endereco: 'ESTRADA RJ CENTO E DEZESSETE, 644 - CINCO LAGOS - MENDES' },
  { id: 'ILH', sigla: 'ILH', nome: 'ILHA DOS POMBOS', endereco: 'ESTRADA ILHA DOS POMBOS, 1 - INFLUENCIA - CARMO' },
  { id: 'MGR', sigla: 'MGR', nome: 'MANGUEIRAL', endereco: 'RUA HENRIQUE DE SOUZA TAVARES - CENTRO(SAP) - SAPUCAIA' },
  { id: 'QTS', sigla: 'QTS', nome: 'QUATIS', endereco: 'RUA AVELINO BATISTA SOARES, 114 - CENTRO(QUAT) - QUATIS' },
  { id: 'LDC', sigla: 'LDC', nome: 'LIDICE', endereco: 'RUA GIUSEPH OLIVEIRA BIONDI, 235 - LIDICE - RIO CLARO' },
  { id: 'APR', sigla: 'APR', nome: 'APARECIDA', endereco: 'RUA JOSE FERNANDES DE SOUZA, 19 - APARECIDA - SAPUCAIA' },
  { id: 'SRA', sigla: 'SRA', nome: 'SERRARIA', endereco: 'RUA FRANCELINO RIBEIRO, 1 - CENTRO(TR) - TRES RIOS' },
  { id: 'EGB', sigla: 'EGB', nome: 'ENGENHEIRO NOBREGA', endereco: 'AVENIDA EXPEDICIONARIO OSWALDO ALMEIDA RAMOS, 5002 - ENGENHEIRO NOBREGA - VASSOURAS' },
  { id: 'AMP', sigla: 'AMP', nome: 'AMPARO', endereco: 'ESTRADA MUNICIPAL, 6 - AMPARO - BARRA MANSA' },
  { id: 'SRI', sigla: 'SRI', nome: 'SANTA RITA', endereco: 'AVENIDA GETULIO VARGAS, 4 - CENTRO(VR) - VOLTA REDONDA' },
  { id: 'DTA', sigla: 'DTA', nome: 'DUTRA', endereco: 'RODOVIA PRESIDENTE DUTRA (LD ESQ) - BOA VISTA - BARRA MANSA' },
  { id: 'ARB', sigla: 'ARB', nome: 'ASSIS RIBEIRO', endereco: 'RUA ASSIS RIBEIRO, 644 - CENTRO(BP) - BARRA DO PIRAI' },
  { id: 'UNS', sigla: 'UNS', nome: 'UNISOL', endereco: 'RUA ALVARO GONCALVES, 279 - CALIFORNIA DA BARRA - BARRA DO PIRAI' },
  { id: 'ATP', sigla: 'ATP', nome: 'ATAULFO DE PAIVA', endereco: 'RODOVIA PRESIDENTE VARGAS, 1 - SANTA CLARA - BARRA MANSA' },
  { id: 'CTL', sigla: 'CTL', nome: 'COTRIL', endereco: 'ESTRADA CARMO, 71 - INFLUENCIA - CARMO' },
  { id: 'VPB', sigla: 'VPB', nome: 'VILA POMBAL', endereco: 'ESTRADA BARRA MANSA, 1 - POMBAL - BARRA MANSA' },
  { id: 'POS', sigla: 'POS', nome: 'POSSE', endereco: 'ESTRADA ILHA DOS POMBOS, 59 - INFLUENCIA - CARMO' },
  { id: 'CMO', sigla: 'CMO', nome: 'CARMO', endereco: 'RUA ALCEU MATTOS, 100 - CARMO - CARMO' },
  { id: 'GVP', sigla: 'GVP', nome: 'GOVERNADOR PORTELA', endereco: 'RUA OSORIO ALMEIDA, 137 - GOVERNADOR PORTELA - MIGUEL PEREIRA' },
  { id: 'PAL', sigla: 'PAL', nome: 'PALMAS', endereco: 'ESTRADA PALMAS, 486 - SACRA FAMILIA DO TINGUA - ENG PAULO DE FRONTIN' },
  { id: 'FMD', sigla: 'FMD', nome: 'FRANCISCO MEDEIROS', endereco: 'RUA VINTE E SETE DE NOVEMBRO, 530 - SANTA CRUZ - VALENCA' },
  { id: 'FME', sigla: 'FME', nome: 'FRANCISCO MEDEIROS', endereco: 'RUA VINTE E SETE DE NOVEMBRO, 530 - SANTA CRUZ - VALENCA' },
  { id: 'LVY', sigla: 'LVY', nome: 'LEVY', endereco: 'RUA REGINALDO MAIA, 134 - FONSECA ALMEIDA - CDOR LEVY GASPARIAN' },
  { id: 'VRD', sigla: 'VRD', nome: 'VOLTA REDONDA', endereco: 'RUA NOSSA SENHORA GRACAS, 92 - SAO GERALDO - VOLTA REDONDA' },
  { id: 'SDD', sigla: 'SDD', nome: 'SAUDADE', endereco: 'RUA JOAQUIM FAGUNDES FERREIRA, 402 - VILA URSULINO - BARRA MANSA' },
  { id: 'CVT', sigla: 'CVT', nome: 'CONSERVATORIA', endereco: 'RUA BRIGIDA MACHADO, 38 - CONSERVATORIA - VALENCA' },
  { id: 'PRP', sigla: 'PRP', nome: 'PARAPEUNA', endereco: 'RODOVIA IRINEU GOUVEIA MAIA, 1 - PARAPEUNA - VALENCA' },
  { id: 'FRR', sigla: 'FRR', nome: 'FERREIROS', endereco: 'ESTRADA RJ CENTO E QUINZE, 12127 - SAO SEBASTIAO FERREIROS - VASSOURAS' },
  { id: 'TBO', sigla: 'TBO', nome: 'TABOAS', endereco: 'RUA OLIER FREITAS SILVEIRA, 368 - TABOAS - RIO DAS FLORES' },
  { id: 'RCL', sigla: 'RCL', nome: 'RIO CLARO', endereco: 'RUA MANOEL PORTUGAL, 280 - CENTRO(RC) - RIO CLARO' },
  { id: 'PTA', sigla: 'PTA', nome: 'PATY DO ALFERES', endereco: 'RUA NOVA MANTIQUIRA, 100 - CENTRO(PA) - PATY DO ALFERES' },
  { id: 'JUN', sigla: 'JUN', nome: 'JUNQUEIRA', endereco: 'AVENIDA MARECHAL PAULO TORRES, 92 - JOSE DE BARROS - VASSOURAS' },
  { id: 'CNN', sigla: 'CNN', nome: 'CANANEIA', endereco: 'ESTRADA CANANEIA, 71 - MASSAMBARA - VASSOURAS' },
  { id: 'SFR', sigla: 'SFR', nome: 'SAO FRANCISCO', endereco: 'ESTRADA QUIRINO, 2999 - ESTEVES - VALENCA' },
  { id: 'IPG', sigla: 'IPG', nome: 'IPIRANGA', endereco: 'AVENIDA INDUSTRIAL, 49 - IPIRANGA - VASSOURAS' },
  { id: 'MCB', sigla: 'MCB', nome: 'MAÇAMBARA', endereco: 'RUA RENATO MARTINS, 1 - MASSAMBARA - VASSOURAS' },
  { id: 'ETV', sigla: 'ETV', nome: 'ESTEVES', endereco: 'ESTRADA QUIRINO, 3000 - ESTEVES - VALENCA' },
  { id: 'JMP', sigla: 'JMP', nome: 'JAMAPARA', endereco: 'AVENIDA PAULINO FERNANDES DA SILVA, 393 - JAMAPARA - SAPUCAIA' },
  { id: 'BCN', sigla: 'BCN', nome: 'BOCAINA', endereco: 'AVENIDA ARISTIDES FERREIRA, 195 - VILA URSULINO - BARRA MANSA' },
  { id: 'SPC', sigla: 'SPC', nome: 'SAPUCAIA', endereco: 'RUA HENRIQUE DE SOUZA TAVARES - CENTRO(SAP) - SAPUCAIA' },
  { id: 'MAZ', sigla: 'MAZ', nome: 'MORRO AZUL', endereco: 'RUA JOAQUIM MENDES, 243 - MORRO AZUL DO TINGUA - ENG PAULO DE FRONTIN' },
  { id: 'MND', sigla: 'MND', nome: 'MENDES', endereco: 'AVENIDA GOVERNADOR ROBERTO SILVEIRA, 20 - INDEPENDENCIA - MENDES' },
  { id: 'PIR', sigla: 'PIR', nome: 'PIRAI', endereco: 'RUA QUINZE DE NOVEMBRO, 370 - CENTRO(PI) - PIRAI' },
  { id: 'ANT', sigla: 'ANT', nome: 'ANTA', endereco: 'RODOVIA BR TREZENTOS NOVENTA TRES LD, 142 - INFLUENCIA - CARMO' },
  { id: 'PFT', sigla: 'PFT', nome: 'PAULO DE FRONTIN NOVA', endereco: 'RODOVIA LUCIANO MEDEIROS, 1485 - PROVISORIA - ENG PAULO DE FRONTIN' },
  { id: 'ARZ', sigla: 'ARZ', nome: 'ARROZAL', endereco: 'ESTRADA JOAO GUIMARAES, 25 - ARROZAL - PIRAI' },
  { id: 'BRP', sigla: 'BRP', nome: 'BARRA DO PIRAI', endereco: 'RUA PREFEITO IAGO JOSE DE CASTRO VALERIO, 1781 - OFICINAS VELHAS - BARRA DO PIRAI' },
  { id: 'STI', sigla: 'STI', nome: 'SANTA ISABEL', endereco: 'RUA JOSE FAGUNDES, 258 - SANTA ISABEL DO RIO PRETO - VALENCA' },
  { id: 'WNK', sigla: 'WNK', nome: 'WERNECK', endereco: 'RUA JOAO AUGUSTO CARVALHO, 48 - WERNECK - PARAIBA DO SUL' },
  { id: 'FLR', sigla: 'FLR', nome: 'FLORIANO', endereco: 'AVENIDA QUINZE DE NOVEMBRO, 220 - CENTRO(BM) - BARRA MANSA' },
  { id: 'BJP', sigla: 'BJP', nome: 'BARAO DE JUPARANA', endereco: 'ESTRADA RJ CENTO E VINTE, 1120 - BARAO DE JUPARANA - VALENCA' },
  { id: 'MGP', sigla: 'MGP', nome: 'MIGUEL PEREIRA', endereco: 'AVENIDA CEZAR LATTES, 12 - CENTRO(MP) - MIGUEL PEREIRA' },
  { id: 'STN', sigla: 'STN', nome: 'SANTANESIA', endereco: 'AVENIDA DARCY VARGAS, 860 - SANTANESIA - PIRAI' },
  { id: 'RTO', sigla: 'RTO', nome: 'RETIRO', endereco: 'AVENIDA SANTA CRUZ, 38 - RETIRO - VOLTA REDONDA' },
  { id: 'VLB', sigla: 'VLB', nome: 'VILA ISABEL', endereco: 'AVENIDA ALAN KARDEK - VILA ISABEL - TRES RIOS' },
  { id: 'SRS', sigla: 'SRS', nome: 'SANTA ROSA', endereco: 'VILA SANTA ROSA, 1 - RIBEIRAO DAS LAGES - PIRAI' },
  { id: 'VLA', sigla: 'VLA', nome: 'VALENÇA NOVA', endereco: 'RUA VINTE E SETE DE NOVEMBRO, 530 - SANTA CRUZ - VALENCA' },
  { id: 'INF', sigla: 'INF', nome: 'INFLUENCIA', endereco: 'ESTRADA CARMO - INFLUENCIA - CARMO' },
  { id: 'ITR', sigla: 'ITR', nome: 'INTEGRAÇÃO', endereco: 'ESTRADA BR ZERO QUARENTA - HERMOGENIO SILVA - TRES RIOS' },
  { id: 'FTL', sigla: 'FTL', nome: 'FONTINELE', endereco: 'AVENIDA DOUTOR FRANCISCO VILELA ANDRADE NETO, 402 - CENTRO(BM) - BARRA MANSA' },
  { id: 'ADP', sigla: 'ADP', nome: 'ANDRADE PINTO', endereco: 'RUA DOMINGOS COELHO SILVA, 191 - ANDRADE PINTO - VASSOURAS' },
  { id: 'PTN', sigla: 'PTN', nome: 'PENTAGNA', endereco: 'ESTRADA FAZENDA CACHOEIRINHA, 9999 - PENTAGNA - VALENCA' },

  // Capital / Zona Sul / Zona Norte / Barra / Jacarepaguá / Centro
  { id: 'HMT', sigla: 'HMT', nome: 'HUMAITÁ', endereco: 'RUA PINHEIRO GUIMARAES, 118 - BOTAFOGO - RIO DE JANEIRO' },
  { id: 'LEM', sigla: 'LEM', nome: 'LEME', endereco: 'RUA GUIMARAES NATAL, 37 - COPACABANA - RIO DE JANEIRO' },
  { id: 'PTS', sigla: 'PTS', nome: 'POSTO SEIS', endereco: 'RUA FRANCISCO OTAVIANO, 159 - IPANEMA - RIO DE JANEIRO' },
  { id: 'ITP', sigla: 'ITP', nome: 'ITAPEBA', endereco: 'AVENIDA CELIA RIBEIRO DA SILVA MENDES, 31 - RECREIO DOS BANDEIRANTES - RIO DE JANEIRO' },
  { id: 'LPD', sigla: 'LPD', nome: 'LEOPOLDO', endereco: 'RUA LEOPOLDO, 840 - ANDARAI - RIO DE JANEIRO' },
  { id: 'CMR', sigla: 'CMR', nome: 'CAMERINO', endereco: 'RUA CAMERINO, 148 - CENTRO(RJ) - RIO DE JANEIRO' },
  { id: 'GNB', sigla: 'GNB', nome: 'GUANABARA', endereco: 'RUA MESTRE RODRIGUES, 136 - TAUA - RIO DE JANEIRO' },
  { id: 'GVD', sigla: 'GVD', nome: 'GOVERNADOR', endereco: 'ESTRADA GALEAO, 2000 - JARDIM CARIOCA - RIO DE JANEIRO' },
  { id: 'FND', sigla: 'FND', nome: 'FUNDAO', endereco: 'AVENIDA BRIGADEIRO TROMPOWSKI, 1150 - ILHA CIDADE UNIVERSITARIA - RIO DE JANEIRO' },
  { id: 'PDG', sigla: 'PDG', nome: 'PORTA D\'AGUA', endereco: 'RUA TIROL, 991 - FREGUESIA - RIO DE JANEIRO' },
  { id: 'TRV', sigla: 'TRV', nome: 'TROVAO', endereco: 'RUA PREFEITO OLIMPIO DE MELO, 961 - VASCO DA GAMA - RIO DE JANEIRO' },
  { id: 'MKZ', sigla: 'MKZ', nome: 'MACKENZIE', endereco: 'RUA ALEXANDRE MACKENZIE, 20 - CENTRO(RJ) - RIO DE JANEIRO' },
  { id: 'RCP', sigla: 'RCP', nome: 'RIO COMPRIDO', endereco: 'RUA BARAO ITAPAGIPE, 605 - TIJUCA - RIO DE JANEIRO' },
  { id: 'BFG', sigla: 'BFG', nome: 'BOTAFOGO', endereco: 'RUA PASSAGEM, 156 - BOTAFOGO - RIO DE JANEIRO' },
  { id: 'BPD', sigla: 'BPD', nome: 'BAEPENDI', endereco: 'RUA CONDE BAEPENDI, 90 - LARANJEIRAS - RIO DE JANEIRO' },
  { id: 'URG', sigla: 'URG', nome: 'URUGUAI', endereco: 'RUA CONDE BONFIM, 859 - TIJUCA - RIO DE JANEIRO' },
  { id: 'BRR', sigla: 'BRR', nome: 'BARRA 2', endereco: 'AVENIDA MONSENHOR ASCANEO - BARRA DA TIJUCA - RIO DE JANEIRO' },
  { id: 'OLP', sigla: 'OLP', nome: 'OLIMPICA', endereco: 'AVENIDA EMBAIXADOR ABELARDO BUENO - BARRA DA TIJUCA - RIO DE JANEIRO' },
  { id: 'TSU', sigla: 'TSU', nome: 'TERMINAL SUL', endereco: 'ESTRADA GROTAO, 1235 - JARDIM BOTANICO - RIO DE JANEIRO' },
  { id: 'LBN', sigla: 'LBN', nome: 'LEBLON', endereco: 'RUA ALMIRANTE GUILHEM, 423 - LEBLON - RIO DE JANEIRO' },
  { id: 'COP', sigla: 'COP', nome: 'COPACABANA', endereco: 'RUA JOSEPH BLOCK, 30 - COPACABANA - RIO DE JANEIRO' },
  { id: 'CMT', sigla: 'CMT', nome: 'CAMPO MARTE', endereco: 'RUA SAO CRISTOVAO, 99999 - SAO CRISTOVAO - RIO DE JANEIRO' },
  { id: 'FCN', sigla: 'FCN', nome: 'FREI CANECA', endereco: 'RUA CAROLINA REIDNER - CATUMBI - RIO DE JANEIRO' },
  { id: 'TRG', sigla: 'TRG', nome: 'TRIAGEM', endereco: 'RUA CONSELHEIRO MAIRINK, 90 - JACARE - RIO DE JANEIRO' },
  { id: 'GLB', sigla: 'GLB', nome: 'GLOBO', endereco: 'ESTRADA CURICICA, 1470 - CURICICA - RIO DE JANEIRO' },
  { id: 'GDN', sigla: 'GDN', nome: 'GARDENIA', endereco: 'RUA ARROIO PAVUNA, 80 - ANIL - RIO DE JANEIRO' },
  { id: 'MBA', sigla: 'MBA', nome: 'METRO BARRA', endereco: 'ESTRADA GAVEA - GAVEA - RIO DE JANEIRO' },
  { id: 'ALC', sigla: 'ALC', nome: 'ALDEIA CAMPISTA', endereco: 'RUA MAXWELL, 46 - VILA ISABEL - RIO DE JANEIRO' },
  { id: 'SMT', sigla: 'SMT', nome: 'SAMARITANO', endereco: 'RUA MINISTRO RAUL FERNANDES, 260 - BOTAFOGO - RIO DE JANEIRO' },
  { id: 'JDB', sigla: 'JDB', nome: 'JARDIM BOTANICO', endereco: 'RUA VISCONDE GRACA, 92 - JARDIM BOTANICO - RIO DE JANEIRO' },
  { id: 'AVD', sigla: 'AVD', nome: 'ALVORADA', endereco: 'RUA JOSE DE FIGUEIREDO, 75 - BARRA DA TIJUCA - RIO DE JANEIRO' },
  { id: 'BAR', sigla: 'BAR', nome: 'BARRA', endereco: 'AVENIDA MONSENHOR ASCANEO - BARRA DA TIJUCA - RIO DE JANEIRO' },
  { id: 'REC', sigla: 'REC', nome: 'RECREIO', endereco: 'RUA ENGENHEIRO WALDYR LEAL LOPES, 99999 - RECREIO DOS BANDEIRANTES - RIO DE JANEIRO' },
  { id: 'SLZ', sigla: 'SLZ', nome: 'SANTA LUZIA', endereco: 'RUA SANTA LUZIA, 615 - CENTRO(RJ) - RIO DE JANEIRO' },
  { id: 'SAT', sigla: 'SAT', nome: 'SANTO ANTONIO', endereco: 'RUA SENADO, 20 - CENTRO(RJ) - RIO DE JANEIRO' },
  { id: 'SCO', sigla: 'SCO', nome: 'SÃO CONRADO', endereco: 'ESTRADA GAVEA - GAVEA - RIO DE JANEIRO' },
  { id: 'CUR', sigla: 'CUR', nome: 'CURICICA', endereco: 'ESTRADA CURICICA, 1470 - CURICICA - RIO DE JANEIRO' },
  { id: 'PBR', sigla: 'PBR', nome: 'PAULA BRITO', endereco: 'RUA SANTO AGOSTINHO, 2 - ANDARAI - RIO DE JANEIRO' },
  { id: 'MJV', sigla: 'MJV', nome: 'MAJOR VAZ', endereco: 'RUA MAJOR RUBENS VAZ - GAVEA - RIO DE JANEIRO' },
  { id: 'BFI', sigla: 'BFI', nome: 'BONFIM', endereco: 'RUA DOUTOR DILERMANDO CRUZ, 20 - TIJUCA - RIO DE JANEIRO' },
  { id: 'PAC', sigla: 'PAC', nome: 'PAC ALEMAO', endereco: 'TRAVESSA CRUZEIRO - INHAUMA - RIO DE JANEIRO' },

  // Zona Oeste / Baixada / Região Metropolitana / Costa Verde
  { id: 'ESP', sigla: 'ESP', nome: 'ESPERANÇA', endereco: 'RUA BOA ESPERANCA, 4830 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'VGE', sigla: 'VGE', nome: 'VIGARIO GERAL', endereco: 'RUA JORNALISTA GERALDO ROCHA, 851 - JARDIM AMERICA - RIO DE JANEIRO' },
  { id: 'VLG', sigla: 'VLG', nome: 'VILA GRACA', endereco: 'RUA B, 12 - SAO PEDRO - SEROPEDICA' },
  { id: 'MRJ', sigla: 'MRJ', nome: 'MARAJOARA', endereco: 'AVENIDA PRESIDENTE TANCREDO NEVES, 1 - MARIA JOSE - JAPERI' },
  { id: 'AUS', sigla: 'AUS', nome: 'AUSTIN', endereco: 'RUA CORONEL MONTEIRO BARROS, 250 - AUSTIN - NOVA IGUACU' },
  { id: 'SRD', sigla: 'SRD', nome: 'SEROPÉDICA', endereco: 'ESTRADA AGUAS LINDAS, 467 - SAO MIGUEL - SEROPEDICA' },
  { id: 'PRS', sigla: 'PRS', nome: 'PARAISO', endereco: 'RUA MAGALHAES BASTOS, 61 - CENTRO(QUEI) - QUEIMADOS' },
  { id: 'CBI', sigla: 'CBI', nome: 'CACHAMBI', endereco: 'RUA CACHAMBI, 301 - CACHAMBI - RIO DE JANEIRO' },
  { id: 'BPN', sigla: 'BPN', nome: 'BRAS DE PINA', endereco: 'RUA OURIQUE, 308 - PENHA CIRCULAR - RIO DE JANEIRO' },
  { id: 'DMC', sigla: 'DMC', nome: 'DEMOCRATICOS', endereco: 'AVENIDA DEMOCRATICOS, 945 - HIGIENOPOLIS - RIO DE JANEIRO' },
  { id: 'VVQ', sigla: 'VVQ', nome: 'VILA VALQUEIRE', endereco: 'RUA GUAPIMIRIM, 24 - VILA VALQUEIRE - RIO DE JANEIRO' },
  { id: 'BMT', sigla: 'BMT', nome: 'BOCA DO MATO', endereco: 'RUA LINS DE VASCONCELOS, 586 - LINS DE VASCONCELOS - RIO DE JANEIRO' },
  { id: 'VTR', sigla: 'VTR', nome: 'VITORIA', endereco: 'ESTRADA GUANDU DO SENA - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'PDD', sigla: 'PDD', nome: 'PIEDADE', endereco: 'RUA GOIAS, 470 - ENGENHO DE DENTRO - RIO DE JANEIRO' },
  { id: 'CLG', sigla: 'CLG', nome: 'COLEGIO', endereco: 'RUA SODRE DA GAMA, 248 - COLEGIO - RIO DE JANEIRO' },
  { id: 'RFR', sigla: 'RFR', nome: 'ROCHA FREIRE', endereco: 'RUA AHIVA, 99999 - ENG ROCHA FREIRE - NOVA IGUACU' },
  { id: 'MTC', sigla: 'MTC', nome: 'MATURACA', endereco: 'RUA TESSALIA, 111 - VILA DA PENHA - RIO DE JANEIRO' },
  { id: 'TUR', sigla: 'TUR', nome: 'TURIACU', endereco: 'ESTRADA SAPE, 1174 - ROCHA MIRANDA - RIO DE JANEIRO' },
  { id: 'VLM', sigla: 'VLM', nome: 'VILA AMERICANA', endereco: 'RUA SAO PAULO - CAMPO ALEGRE - QUEIMADOS' },
  { id: 'CAB', sigla: 'CAB', nome: 'CABUCU', endereco: 'RUA ROSARIO, 1 - JARDIM LARANJEIRAS - NOVA IGUACU' },
  { id: 'JAB', sigla: 'JAB', nome: 'JABOATAO', endereco: 'RUA JABOATAO, 22 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'CRO', sigla: 'CRO', nome: 'COELHO DA ROCHA', endereco: 'RUA IRIDIUM, 273 - COELHO DA ROCHA - SAO JOAO DE MERITI' },
  { id: 'TQR', sigla: 'TQR', nome: 'TAQUARA', endereco: 'RUA JORDAO, 321 - TANQUE - RIO DE JANEIRO' },
  { id: 'NIG', sigla: 'NIG', nome: 'NOVA IGUACU', endereco: 'RUA CORONEL FRANCISCO SOARES, 600 - CENTRO(NI) - NOVA IGUACU' },
  { id: 'TFL', sigla: 'TFL', nome: 'TEOFILO', endereco: 'RUA ABATOS, 129 - ENGENHEIRO PEDREIRA - JAPERI' },
  { id: 'PTC', sigla: 'PTC', nome: 'PONTE COBERTA', endereco: 'ESTRADA EDUARDO PEREIRA DIAS JUNIOR - LAGES - PARACAMBI' },
  { id: 'MGC', sigla: 'MGC', nome: 'MIGUEL COUTO', endereco: 'AVENIDA RIO D\'OURO, 99999 - ITAIPU - BELFORD ROXO' },
  { id: 'PII', sigla: 'PII', nome: 'PIAI', endereco: 'ESTRADA PIAI, 1 - GUARATIBA - RIO DE JANEIRO' },
  { id: 'PDR', sigla: 'PDR', nome: 'PEDREIRA', endereco: 'AVENIDA SENHOR BONFIM, 10 - ENGENHEIRO PEDREIRA - JAPERI' },
  { id: 'STS', sigla: 'STS', nome: 'SANTISSIMO', endereco: 'RUA CAMPINA GRANDE, 156 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'LAG', sigla: 'LAG', nome: 'LAGES', endereco: 'RUA ROMARIO NETO, 1533 - GUARAJUBA - PARACAMBI' },
  { id: 'AIM', sigla: 'AIM', nome: 'AIMORES', endereco: 'RUA BALBINA RIBEIRO, 221 - RIACHAO - NOVA IGUACU' },
  { id: 'PRM', sigla: 'PRM', nome: 'PIRANEMA', endereco: 'RUA MANOEL DE SOUZA, 2 - PARQUE JACIMAR - SEROPEDICA' },
  { id: 'CLN', sigla: 'CLN', nome: 'COLONIAL', endereco: 'PRACA MANOEL ANTONIO PEREIRA, 1 - PIRANEMA - ITAGUAI' },
  { id: 'CPV', sigla: 'CPV', nome: 'CAPIVARI', endereco: 'RUA CRATEUS, 99999 - CHACARAS RIO PETROPOLIS - DUQUE DE CAXIAS' },
  { id: 'BRI', sigla: 'BRI', nome: 'BRISAMAR', endereco: 'RODOVIA RIO SANTOS, 36 - ENGENHO - ITAGUAI' },
  { id: 'PRC', sigla: 'PRC', nome: 'PARACAMBI', endereco: 'RUA JOSE CANDIDO COSTA CORTES, 253 - CENTRO(PAR) - PARACAMBI' },
  { id: 'RST', sigla: 'RST', nome: 'RIO SANTOS', endereco: 'RODOVIA RIO SANTOS, 18 - BRISAMAR - ITAGUAI' },
  { id: 'CAL', sigla: 'CAL', nome: 'CAMPO ALEGRE', endereco: 'RUA SAO PAULO, 35 - CAMPO ALEGRE - QUEIMADOS' },
  { id: 'MGA', sigla: 'MGA', nome: 'MAGARÇA', endereco: 'ESTRADA PEDRA, 165 - SANTA CRUZ - RIO DE JANEIRO' },
  { id: 'IMD', sigla: 'IMD', nome: 'ILHA DA MADEIRA', endereco: 'ESTRADA JOSE MIRANDA OLIVEIRA, 21 - ILHA DA MADEIRA - ITAGUAI' },
  { id: 'ELD', sigla: 'ELD', nome: 'ELDORADO', endereco: 'RUA JOAO RIBEIRO, 99999 - VILA CENTENARIO - DUQUE DE CAXIAS' },
  { id: 'UNV', sigla: 'UNV', nome: 'UNIVERSIDADE', endereco: 'ESTRADA RIO SAO PAULO, 1 - SANTA SOFIA - SEROPEDICA' },
  { id: 'GTB', sigla: 'GTB', nome: 'GUARATIBA', endereco: 'ESTRADA GROTA FUNDA - GUARATIBA - RIO DE JANEIRO' },
  { id: 'CDR', sigla: 'CDR', nome: 'CAÇADOR', endereco: 'ESTRADA CACADOR, 1 - RAIZ DA SERRA - ITAGUAI' },
  { id: 'VDN', sigla: 'VDN', nome: 'VERIDIANA', endereco: 'ESTRADA SEPETIBA, 11 - SEPETIBA - RIO DE JANEIRO' },
  { id: 'MTO', sigla: 'MTO', nome: 'MATO ALTO', endereco: 'AVENIDA PROFESSOR MARIO PEDROSA, 99999 - GUARATIBA - RIO DE JANEIRO' },
  { id: 'STC', sigla: 'STC', nome: 'SANTA CLARA', endereco: 'RUA VEREADOR JOSE VIRGILIO DO PRADO, 233 - VILA NASCENTE - QUEIMADOS' },
  { id: 'ZPL', sigla: 'ZPL', nome: 'ZEPELIM', endereco: 'ESTRADA SEPETIBA, 9999 - SANTA CRUZ - RIO DE JANEIRO' },
  { id: 'TUT', sigla: 'TUT', nome: 'TUIUTI', endereco: 'RUA TUIUTI, 9999 - PARQUE ESTORIL - NOVA IGUACU' },
  { id: 'STP', sigla: 'STP', nome: 'SANTA PERCILIANA', endereco: 'RUA CORONEL FRANCA SOARES, 99999 - FIGUEIRAS - NOVA IGUACU' },
  { id: 'AMR', sigla: 'AMR', nome: 'AMERICAS', endereco: 'AVENIDA BARAO COCAIS, 9999 - GUARATIBA - RIO DE JANEIRO' },
  { id: 'MRP', sigla: 'MRP', nome: 'MARAPICU', endereco: 'AVENIDA ABILIO AUGUSTO TAVORA - PARAISO - NOVA IGUACU' },
  { id: 'AFR', sigla: 'AFR', nome: 'ARI FRANCO', endereco: 'ESTRADA ENGENHO, 2071 - BANGU - RIO DE JANEIRO' },
  { id: 'PMG', sigla: 'PMG', nome: 'PADRE MIGUEL', endereco: 'RUA GENERAL AZEREDO, 1009 - REALENGO - RIO DE JANEIRO' },
  { id: 'CAM', sigla: 'CAM', nome: 'CAMARA', endereco: 'AVENIDA CARLOS SAMPAIO CORREIA, 111 - BANGU - RIO DE JANEIRO' },
  { id: 'KND', sigla: 'KND', nome: 'KENEDY', endereco: 'AVENIDA BRASIL, 34999 - BANGU - RIO DE JANEIRO' },
  { id: 'ABR', sigla: 'ABR', nome: 'AREIA BRANCA', endereco: 'RUA DONA ODETE, 326 - DIMAS FILHO - BELFORD ROXO' },
  { id: 'IMT', sigla: 'IMT', nome: 'INMETRO', endereco: 'AVENIDA NOSSA SENHORA GRACAS, 50 - FNM - DUQUE DE CAXIAS' },
  { id: 'JPR', sigla: 'JPR', nome: 'JAPERI', endereco: 'RUA MIGUEL PEREIRA, 246 - VILA PLANETARIA - JAPERI' },
  { id: 'CGR', sigla: 'CGR', nome: 'CAMPO GRANDE', endereco: 'RUA CAMPO FORMOSO, 1456 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'CPN', sigla: 'CPN', nome: 'CAMPINA', endereco: 'RUA CAMPINA GRANDE, 156 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'PER', sigla: 'PER', nome: 'PEDRO ERNESTO', endereco: 'RUA ELEUTERIO MOTA, 545 - OLARIA - RIO DE JANEIRO' },
  { id: 'QCS', sigla: 'QCS', nome: 'QUINCAS', endereco: 'ESTRADA MENDANHA, 4420 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'SPB', sigla: 'SPB', nome: 'SEPETIBA', endereco: 'RUA CARMELIA DUARTE, 53 - SEPETIBA - RIO DE JANEIRO' },
  { id: 'CHR', sigla: 'CHR', nome: 'CACHAMORRA', endereco: 'ESTRADA MONTEIRO, 887 - CAMPO GRANDE - RIO DE JANEIRO' },
  { id: 'PVN', sigla: 'PVN', nome: 'PAVUNA', endereco: 'AVENIDA CHRISOSTOMO PIMENTEL OLIVEIRA, 1184 - ANCHIETA - RIO DE JANEIRO' },
  { id: 'VTL', sigla: 'VTL', nome: 'VILAR DOS TELES', endereco: 'AVENIDA AUTOMOVEL CLUBE, 90 - GLAUCIA - BELFORD ROXO' },
  { id: 'SJO', sigla: 'SJO', nome: 'SÃO JOÃO', endereco: 'BOULEVARD OLAVO BILAC - JARDIM OLAVO BILAC - DUQUE DE CAXIAS' },
  { id: 'SRP', sigla: 'SRP', nome: 'SARAPUI', endereco: 'RUA ALEXANDRINO PINTO, 99999 - PARQUE MUISA - DUQUE DE CAXIAS' },
  { id: 'VIL', sigla: 'VIL', nome: 'VILA DE CAVA', endereco: 'RUA ANTONIO, 999 - VILA DE CAVA - NOVA IGUACU' },
  { id: 'CSO', sigla: 'CSO', nome: 'COMENDADOR SOARES', endereco: 'RUA MINISTRO LAFAIETE DE ANDRADE, 1 - COMENDADOR SOARES - NOVA IGUACU' },
  { id: 'CMS', sigla: 'CMS', nome: 'COSMOS', endereco: 'ESTRADA PACIENCIA, 1238 - COSMOS - RIO DE JANEIRO' },
  { id: 'GDL', sigla: 'GDL', nome: 'GUADALUPE', endereco: 'ESTRADA ALMIRANTE SANTIAGO DANTAS, 610 - BARROS FILHO - RIO DE JANEIRO' },
  { id: 'ZIN', sigla: 'ZIN', nome: 'ZONA INDUSTRIAL', endereco: 'RUA AGUANIL, 390 - SANTA CRUZ - RIO DE JANEIRO' },
  { id: 'MRT', sigla: 'MRT', nome: 'MERITI', endereco: 'RUA DOUTOR JOSE SOARES, 236 - PARQUE ANALANDIA - SAO JOAO DE MERITI' },
  { id: 'CCD', sigla: 'CCD', nome: 'CASCADURA', endereco: 'AVENIDA ERNANI CARDOSO, 154 - CASCADURA - RIO DE JANEIRO' },
  { id: 'SLO', sigla: 'SLO', nome: 'SAO LOURENCO', endereco: 'ESTRADA SAO LOURENCO - CHACARAS RIO PETROPOLIS - DUQUE DE CAXIAS' },
  { id: 'ITG', sigla: 'ITG', nome: 'ITAGUAI', endereco: 'RUA SANTA CRUZ, 99999 - TEIXEIRA - ITAGUAI' },
  { id: 'PCI', sigla: 'PCI', nome: 'PACIENCIA', endereco: 'ESTRADA SANTA EUGENIA - PACIENCIA - RIO DE JANEIRO' },
  { id: 'CXS', sigla: 'CXS', nome: 'CAXIAS', endereco: 'RUA SEABRA SOBRINHO, 1000 - VILA CENTENARIO - DUQUE DE CAXIAS' },
  { id: 'RDO', sigla: 'RDO', nome: 'RIO DOURO', endereco: 'RUA ARMANDO DIAS PEREIRA - ADRIANOPOLIS - NOVA IGUACU' },
  { id: 'TER', sigla: 'TER', nome: 'TERRA NOVA', endereco: 'AVENIDA ITAOCA, 2284 - BONSUCESSO - RIO DE JANEIRO' },
  { id: 'MNG', sigla: 'MNG', nome: 'MANGUARIBA', endereco: 'ESTRADA LAMA PRETA - SANTA CRUZ - RIO DE JANEIRO' },
  { id: 'CMJ', sigla: 'CMJ', nome: 'CARAMUJOS', endereco: 'AVENIDA PRESIDENTE TANCREDO NEVES - ENGENHEIRO PEDREIRA - JAPERI' },
  { id: 'WLS', sigla: 'WLS', nome: 'WASHINGTON LUIS', endereco: 'RUA AUGUSTO LIMA, 840 - CENTRO(DC) - DUQUE DE CAXIAS' },
  { id: 'MZB', sigla: 'MZB', nome: 'MAZOMBA', endereco: 'ESTRADA MAZOMBA, 1150 - MAZOMBA - ITAGUAI' },
  { id: 'QMD', sigla: 'QMD', nome: 'QUEIMADOS', endereco: 'RUA ALMEZINA LEAL DE SOUZA, 166 - JARDIM DO TREVO - QUEIMADOS' },
  { id: 'ROS', sigla: 'ROS', nome: 'ROSALI', endereco: 'RUA SENADOR SILVIO HECK ALMIRANTE, 99999 - JARDIM MERITI - SAO JOAO DE MERITI' },
  { id: 'RAM', sigla: 'RAM', nome: 'RAMOS', endereco: 'AVENIDA CAMPEOES, 601 - RAMOS - RIO DE JANEIRO' },
  { id: 'MNB', sigla: 'MNB', nome: 'MENA BARRETO', endereco: 'RUA MAGNO DE CARVALHO, 96 - EDSON PASSOS - MESQUITA' },
  { id: 'AGR', sigla: 'AGR', nome: 'AGUA GRANDE', endereco: 'RUA BARAO MELGACO, 1251 - CORDOVIL - RIO DE JANEIRO' },
  { id: 'MRN', sigla: 'MRN', nome: 'MARCONE', endereco: 'ESTRADA MATO GROSSO - CAMPO ALEGRE - NOVA IGUACU' },
  { id: 'MML', sigla: 'MML', nome: 'MARMELO', endereco: 'ESTRADA MATO ALTO - GUARATIBA - RIO DE JANEIRO' },
  { id: 'PLM', sigla: 'PLM', nome: 'PALMARES', endereco: 'ESTRADA FURADO, 376 - PACIENCIA - RIO DE JANEIRO' },
  { id: 'BML', sigla: 'BML', nome: 'BERNARDINO DE MELO', endereco: 'AVENIDA GOVERNADOR AMARAL PEIXOTO - CENTRO(NI) - NOVA IGUACU' },
  { id: 'CRM', sigla: 'CRM', nome: 'CARMARI', endereco: 'RUA CONDE IRAJA - BOTAFOGO - NOVA IGUACU' },
  { id: 'DCT', sigla: 'DCT', nome: 'DEL CASTILHO', endereco: 'AVENIDA SEGAL - DEL CASTILHO - RIO DE JANEIRO' },
  { id: 'CRD', sigla: 'CRD', nome: 'CARANDÁ', endereco: 'RUA FONTOURA CHAVES, 77 - AGUA SANTA - RIO DE JANEIRO' },
  { id: 'LIN', sigla: 'LIN', nome: 'LINS', endereco: 'RUA LINS DE VASCONCELOS - LINS DE VASCONCELOS - RIO DE JANEIRO' },
  { id: 'CDV', sigla: 'CDV', nome: 'CORDOVIL', endereco: 'RUA CORONEL CAMISAO - CORDOVIL - RIO DE JANEIRO' },
  { id: 'OLR', sigla: 'OLR', nome: 'OLARIA', endereco: 'RUA MINISTRO MOREIRA ABREU, 515 - OLARIA - RIO DE JANEIRO' }
];
