import { Subestacao } from './types';

export const SUBESTACOES: Subestacao[] = [
  { id: 'CCD', sigla: 'CCD', nome: 'CASCADURA', endereco: 'AVENIDA ERNANI CARDOSO, 154 - CASCADURA - RJ' },
  { id: 'BPN', sigla: 'BPN', nome: 'BRÁS DE PINA', endereco: 'RUA OURIQUE, Nº 285 - PENHA CIRCULAR' },
  { id: 'AGR', sigla: 'AGR', nome: 'ÁGUA GRANDE', endereco: 'RUA BARÃO DE MELGAÇO, Nº 1255 - CORDOVIL' },
  { id: 'BMT', sigla: 'BMT', nome: 'BOCA DO MATO', endereco: 'RUA LINS DE VASCONCELOS, Nº 586 - LINS' },
  { id: 'CBI', sigla: 'CBI', nome: 'CACHAMBI', endereco: 'RUA CACHAMBI, Nº 301 - CACHAMBI' },
  { id: 'CDV', sigla: 'CDV', nome: 'CORDOVIL', endereco: 'RUA CORONEL CAMISÃO, Nº 1217 - CORDOVIL' },
  { id: 'CLG', sigla: 'CLG', nome: 'COLÉGIO', endereco: 'RUA SODRÉ DA GAMA, Nº 248 - COLÉGIO' },
  { id: 'CRD', sigla: 'CRD', nome: 'CARANDA', endereco: 'RUA FONTOURA CHAVES, 24 - PIEDADE' },
  { id: 'DCT', sigla: 'DCT', nome: 'DEL CASTILHO', endereco: 'AV. SEGAL, Nº 373 - DEL CASTILHO' },
  { id: 'DMC', sigla: 'DMC', nome: 'DEMOCRÁTICOS', endereco: 'AV. DOS DEMOCRÁTICOS, Nº 911 - HIGIENÓPOLIS' },
  { id: 'GDL', sigla: 'GDL', nome: 'GUADALUPE', endereco: 'EST. ALM. SANTIAGO DANTAS, 610 - GUADALUPE' },
  { id: 'LIN', sigla: 'LIN', nome: 'LINS', endereco: 'RUA N.S.ª DA GUIA, Nº 209 - LINS' },
  { id: 'MRT', sigla: 'MRT', nome: 'MERITI', endereco: 'RUA DR. JOSÉ SOARES, Nº 219 - P. ANANLÂNDIA' },
  { id: 'MTC', sigla: 'MTC', nome: 'MATURACÁ', endereco: 'AV. BRÁS DE PINA, Nº 1173 - VILA DA PENHA' },
  { id: 'OLR', sigla: 'OLR', nome: 'OLARIA', endereco: 'RUA MIN. MOREIRA DE ABREU, Nº 517 - OLARIA' },
  { id: 'PDD', sigla: 'PDD', nome: 'PIEDADE', endereco: 'RUA GOIÁS, Nº 470 - PIEDADE' },
  { id: 'PER', sigla: 'PER', nome: 'PEDRO ERNESTO', endereco: 'RUA ELEUTÉRIO DA MOTA, Nº 545 - OLARIA' },
  { id: 'RAM', sigla: 'RAM', nome: 'RAMOS', endereco: 'AV. DOS CAMPEÕES, Nº 601 - RAMOS' },
  { id: 'TER', sigla: 'TER', nome: 'TERRA NOVA', endereco: 'AV. ITAOCA, Nº 2284 - INHAÚMA' },
  { id: 'TUR', sigla: 'TUR', nome: 'TURIAÇU', endereco: 'ESTR. DO SAPÊ, Nº 1174 - TURIAÇU' },
  { id: 'VGE', sigla: 'VGE', nome: 'VIGÁRIO GERAL', endereco: 'RUA JORNALISTA GERALDO ROCHA, Nº 873 - J. AMÉRICA' },
  { id: 'WLS', sigla: 'WLS', nome: 'WASHINGTON LUÍS', endereco: 'AV. PRESIDENTE KENNEDY, Nº 690 - CENTRO - D. CAXIAS' },
  { id: 'STS', sigla: 'STS', nome: 'SANTÍSSIMO', endereco: 'RUA CAMPINA GRANDE, S/Nº - CAMPO GRANDE' },
  { id: 'AFR', sigla: 'AFR', nome: 'ARI FRANCO', endereco: 'ESTRADA DO ENGENHO, Nº 1887 - BANGU' },
  { id: 'BRI', sigla: 'BRI', nome: 'BRISAMAR', endereco: 'ROD. RIO SANTOS, KM 19,5 - ITAGUAÍ' },
  { id: 'CAM', sigla: 'CAM', nome: 'CAMARÁ', endereco: 'AV. CARLOS SAMPAIO CORREIA, 181 - SENADOR CAMARÁ' },
  { id: 'CHR', sigla: 'CHR', nome: 'CACHAMORRA', endereco: 'ESTR. DO MONTEIRO, Nº 887' },
  { id: 'CMS', sigla: 'CMS', nome: 'COSMOS', endereco: 'ESTR. DA PACIÊNCIA, Nº 3950 - PACIÊNCIA' },
  { id: 'ESP', sigla: 'ESP', nome: 'ESPERANÇA', endereco: 'ESTRADA DE URUCÂNIA Nº 4780 - STA. CRUZ' },
  { id: 'ITG', sigla: 'ITG', nome: 'ITAGUAÍ', endereco: 'AV. AYRTON SENNA, S/N - ITAGUAÍ' },
  { id: 'JAB', sigla: 'JAB', nome: 'JABOATÃO', endereco: 'RUA JABOATÃO, Nº 22 - CAMPO GRANDE' },
  { id: 'MRP', sigla: 'MRP', nome: 'MARAPICU', endereco: 'AV. ABÍLIO AUGUSTO TÁVORA, S/Nº 14435' },
  { id: 'MTO', sigla: 'MTO', nome: 'MATO ALTO', endereco: 'AV. ALHAMBRA, Nº 494 - GUARATIBA' },
  { id: 'PCI', sigla: 'PCI', nome: 'PACIÊNCIA', endereco: 'ESTRADA DE SANTA EUGÊNIA, 2600 - PACIÊNCIA' },
  { id: 'PLM', sigla: 'PLM', nome: 'PALMARES', endereco: 'ESTR. DO FURADO, Nº 385 - PACIÊNCIA' },
  { id: 'PMG', sigla: 'PMG', nome: 'PADRE MIGUEL', endereco: 'RUA GAL. AZEREDO, Nº 1010 - REALENGO' },
  { id: 'TQR', sigla: 'TQR', nome: 'TAQUARA', endereco: 'RUA JORDÃO, Nº 225 - TAQUARA' },
  { id: 'VVQ', sigla: 'VVQ', nome: 'VILA VALQUEIRE', endereco: 'RUA GUAPIMIRIM, Nº 24 - VILA VALQUEIRE' },
  { id: 'ZIN', sigla: 'ZIN', nome: 'ZONA INDUSTRIAL', endereco: 'RUA AGUANIL, Nº 390 - SANTA CRUZ' },
  { id: 'NIG', sigla: 'NIG', nome: 'NOVA IGUAÇU', endereco: 'AV. CEL. FRANCISCO SOARES, 385 - N. IGUAÇU' },
  { id: 'CRM', sigla: 'CRM', nome: 'CARMARI', endereco: 'EST. SANTA RITA, 40 - S. LUIZ GONZAGA - NOVA IGUAÇU' },
  { id: 'ABR', sigla: 'ABR', nome: 'AREIA BRANCA', endereco: 'RUA VARGAS COUTINHO, Nº 71 - PIAM - BELFORD ROXO' },
  { id: 'BML', sigla: 'BML', nome: 'BERNARDINO DE MELO', endereco: 'AV. GOV. AMARAL PEIXOTO C/TRAV. - N. IGUAÇU' },
  { id: 'CRO', sigla: 'CRO', nome: 'COELHO DA ROCHA', endereco: 'RUA VER. CELSO MOREIRA GUERRA, 109 - PARQUE ALIAN' },
  { id: 'CSO', sigla: 'CSO', nome: 'COM. SOARES', endereco: 'RUA MIN. LAFAYETE DE ANDRADE, Nº 1180 - JARDIM LUMAR' },
  { id: 'CXS', sigla: 'CXS', nome: 'CAIXAS', endereco: 'RUA SEABRA SOBRINHO, Nº 1000 - CENTENÁRIO' },
  { id: 'ELD', sigla: 'ELD', nome: 'ELDORADO', endereco: 'RUA IBIRARUMA, S/Nº - P. ELDORADO' },
  { id: 'IMT', sigla: 'IMT', nome: 'INMETRO', endereco: 'AV. N. SRA. DAS GRAÇAS, Nº 0 - P. OPERÁRIA' },
  { id: 'MNB', sigla: 'MNB', nome: 'MENA BARRETO', endereco: 'AV. PRES. COSTA E SILVA, Nº 125 - EDSON PASSOS' },
  { id: 'PVN', sigla: 'PVN', nome: 'PAVUNA', endereco: 'AV. CHRYSÓSTOMO PIMENTEL DE OLIVEIRA, 1254 - PAVUNA' },
  { id: 'QMD', sigla: 'QMD', nome: 'QUEIMADOS', endereco: 'R. DO ROSÁRIO, 644 - QUEIMADOS' },
  { id: 'RFR', sigla: 'RFR', nome: 'ROCHA FREIRE', endereco: 'RUA AHIVA, Nº 586 - SANTA RITA' },
  { id: 'ROS', sigla: 'ROS', nome: 'ROSALI', endereco: 'RUA SENADOR TARCÍSIO MEIRA, Nº 500 - VILA ROSALI' },
  { id: 'SJO', sigla: 'SJO', nome: 'MERITI', endereco: 'AV. DO COMÉRCIO, S/N / RUA PEDRO LESSA, S/N' },
  { id: 'SRD', sigla: 'SRD', nome: 'SEROPÉDICA', endereco: 'ESTRADA DAS ÁGUAS LINDAS, 463' },
  { id: 'SRP', sigla: 'SRP', nome: 'SARAPUÍ', endereco: 'RUA ALEXANDRINO PINTO, Nº 794 - CAIXAS' },
  { id: 'STC', sigla: 'STC', nome: 'SANTA CLARA', endereco: 'RUA VEREADOR JOSÉ VIRGÍLIO DO PRADO, Nº 113' },
  { id: 'VIL', sigla: 'VIL', nome: 'VILAR DOS TELES', endereco: 'AV. AUTOMÓVEL CLUBE, Nº 590 - SÃO JOSÉ - BELFORD ROXO' }
];
